name: Warm up Render (GET via Actions)

on:
  schedule:
    - cron: "*/10 * * * *"   # каждые 10 минут
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: GET /healthz (robust warmup)
        run: |
          set -e
          URL="https://my-learning-repository.onrender.com/healthz"
          echo "GET -> $URL"
          # Пояснения:
          # -sS               : тихий режим, но ошибки показываем
          # -4                : форсируем IPv4 (иногда сетка GHA мудрит с IPv6)
          # --fail            : падать на 4xx/5xx
          # --connect-timeout : таймаут только на TCP-коннект
          # --max-time        : общий таймаут на попытку
          # --retry
