name: Warm up Render (GET via Actions)

on:
  schedule:
    # GitHub Actions крутит CRON по UTC.
    # Сдвинем на 3-й минуте, потом каждые 10, чтобы реже совпадать с UptimeRobot.
    - cron: "3/10 * * * *"
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: GET /healthz (robust warmup)
        run: |
          set -e
          URL="https://srbija-struja.onrender.com/healthz?src=gha"
          echo "GET -> $URL"
          curl -v -sS -4 \
               -H "User-Agent: GHA-Warmup" \
               --fail \
               --connect-timeout 10 \
               --max-time 60 \
               --retry 6 \
               --retry-delay 10 \
               --retry-all-errors \
               "$URL" >/dev/null
          echo "OK: GET 200 /healthz"
